pipeline {
    agent any
    parameters {
        string(name: 'FILE_PATH_PARAM', description: 'Enter the file input.xls path', defaultValue: 'C:\\_GIT\\satur\\input.xls')
        string(name: 'ROBOT_PARAMS', description: 'Additional RF params (empty for nothing)', defaultValue: '')
    }
    stages {                        
        stage('Copy File to Workspace') {
            steps {
                script {
                    def filePath = params.FILE_PATH_PARAM

                    // Kontrola, zda zadaná cesta k souboru existuje
                    if (fileExists(filePath)) {
                        echo "Copying file from ${filePath} to workspace..."
                        // Kopírování souboru do workspace
                        bat "copy \"${filePath}\" .\\RobotFramework\\input.xls"
                    } else {
                        error "Specified file path does not exist: ${filePath}"
                    }
                }
            }
        }        
        stage('GIT clone') {
            steps {
                git branch: 'main', url: 'https://github.com/Tesena-smart-testing/satur_demo.git'
            }
        }
        stage('Run script') {
            steps {
                script {
                    def rfParam = params.ROBOT_PARAMS
                }
                bat "cd RobotFramework && dir && robot \"${rfParam}\" .\\test.robot"
            }
        }
        stage('Archive artefacts') {
            steps {
                archiveArtifacts artifacts: 'RobotFramework/output*.xlsx, RobotFramework/data*.json, RobotFramework/log.html', followSymlinks: false
            }
        }                
    }
    post {
        always {
            // Ujistíme se, že workspace je uklizen
            cleanWs()
        }
    }
}