pipeline {
    agent any
    parameters {
        file(name: 'INPUTFILE', description: 'Select a file to process')
    }
    stages {                        
        stage('Replace File') {
            steps {
                script {
                    def selectedFile = parameters.INPUTFILE
                    def workspace = pwd() // Získání cesty k workspace
                    echo "Selected file: ${selectedFile}"
                    //sh "cp ${selectedFile} ${workspace}/input2.xls"
                    bat "copy /Y \"${selectedFile}\" \"${workspace}\\input2.xls\""
                }
            }
        }        
        stage('Echo') {
            steps {
                bat 'echo %INPUTFILE%'
            }
        }
        stage('GIT clone') {
            steps {
                git branch: 'main', url: 'https://github.com/Tesena-smart-testing/satur_demo.git'
            }
        }
        stage('Run script') {
            steps {
                bat 'dir && cd RobotFramework && dir && robot .\\test.robot'
            }
        }
        stage('Archive artefacts') {
            steps {
                archiveArtifacts artifacts: 'RobotFramework/output*.xlsx, RobotFramework/data*.json, RobotFramework/log.html', followSymlinks: false
            }
        }
        stage('CleanWS') {
            steps {
                cleanWs notFailBuild: true
            }
        }        
    }
}